-- Book-style percussion for every pattern. The member staff reads strings
-- prefixed with drum: (snare middle space, kick bottom space, hi-hat foot X).

UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*16' WHERE slug = 'single-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 sn16 sn16 ^sn16]*4' WHERE slug = 'single-stroke-four';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 sn16 sn16 sn16 sn16 sn16 ^sn8]*2' WHERE slug = 'single-stroke-seven';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:zsn4*4' WHERE slug = 'multiple-bounce-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:(sn8 sn8 sn8)*4' WHERE slug = 'triple-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*16' WHERE slug = 'double-stroke-open-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 sn16 sn16 sn16 ^sn8 r8]*2' WHERE slug = 'five-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[^sn8 sn16 sn16 sn16 sn16 ^sn8]*2' WHERE slug = 'six-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 sn16 sn16 sn16 sn16 sn16 ^sn8]*2' WHERE slug = 'seven-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*8 ^sn8 r8 r4' WHERE slug = 'nine-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*8 ^sn8 ^sn8 r4' WHERE slug = 'ten-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*10 ^sn8 r4' WHERE slug = 'eleven-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*12 ^sn8 r8' WHERE slug = 'thirteen-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn16*14 ^sn8' WHERE slug = 'fifteen-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:5/4 sn16*16 ^sn8 r8' WHERE slug = 'seventeen-stroke-roll';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[^sn16 sn16 sn16 sn16 ^sn16 sn16 sn16 sn16]*2' WHERE slug = 'single-paradiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:(^sn8 sn8 sn8) (sn8 sn8 sn8) (^sn8 sn8 sn8) (sn8 sn8 sn8)' WHERE slug = 'double-paradiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[^sn16 sn16 sn16 sn16 sn16 sn16 sn16 sn16]*2' WHERE slug = 'triple-paradiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:12/8 ^sn8 sn8 sn8 sn8 sn8 sn8 ^sn8 sn8 sn8 sn8 sn8 sn8' WHERE slug = 'single-paradiddle-diddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:fsn4*4' WHERE slug = 'flam';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:(^fsn8 sn8 sn8)*4' WHERE slug = 'flam-accent';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 sn16 fsn16 sn16]*4' WHERE slug = 'flam-tap';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 ^sn16 sn16 sn16 fsn16 r16]*2 r4' WHERE slug = 'flamacue';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 sn16 sn16 sn16 fsn16 sn16 sn16 sn16]*2' WHERE slug = 'flam-paradiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 sn16 sn16 sn16 fsn16 sn16 sn16 sn16]*2' WHERE slug = 'single-flammed-mill';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 sn16 sn16 sn16 sn16 sn16 sn16 r16]*2' WHERE slug = 'flam-paradiddle-diddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 sn16 sn16 fsn16]*4' WHERE slug = 'pataflafla';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:(fsn8 sn8 sn8)*4' WHERE slug = 'swiss-army-triplet';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:fsn8*8' WHERE slug = 'inverted-flam-tap';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn8 dsn8 ^sn8 r8]*2' WHERE slug = 'flam-drag';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:dsn4*4' WHERE slug = 'drag';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[dsn8 sn8]*4' WHERE slug = 'single-drag-tap';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[dsn8 dsn8 ^sn8 r8]*2' WHERE slug = 'double-drag-tap';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[dsn8 sn8 sn8 r8]*2' WHERE slug = 'lesson-25';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 dsn16 sn16 sn16 sn16 r16]*2 r4' WHERE slug = 'single-dragadiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[^sn16 dsn16 sn16 sn16 sn16 r16]*2 r4' WHERE slug = 'drag-paradiddle-1';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[^sn16 ^sn16 dsn16 sn16 sn16 sn16]*2 r4' WHERE slug = 'drag-paradiddle-2';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[dsn8 sn8 sn8 ^sn8]*2' WHERE slug = 'single-ratamacue';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:dsn8 dsn8 sn8 sn8 ^sn8 r8 r4' WHERE slug = 'double-ratamacue';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:dsn8 dsn8 dsn8 sn8 sn8 ^sn8 r8 r4' WHERE slug = 'triple-ratamacue';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[csn16 sn16 sn16 sn16 csn16 sn16 sn16 sn16]*2' WHERE slug = 'cheese-paradiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[csn16 sn16 sn16 sn16 csn16 sn16 sn16 sn16]*2' WHERE slug = 'cheese-invert';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[fsn16 sn16 sn16 sn16]*4' WHERE slug = 'swiss-tap';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:dsn8 sn8 dsn8 sn8 ^sn8 r8 r4' WHERE slug = 'blue-rudiment';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[csn16 sn16 sn16 csn16]*4' WHERE slug = 'cheese-pataflafla';

UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:bd8*8' WHERE slug = 'kick-singles';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:bd8 ph8 bd8 ph8 bd8 ph8 bd8 ph8' WHERE slug = 'foot-alternate';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:bd16*16' WHERE slug = 'kick-doubles';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:ph4*4' WHERE slug = 'hihat-foot-quarters';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:bd16*16' WHERE slug = 'heel-toe-doubles';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:(bd8 bd8 bd8)*4' WHERE slug = 'kick-triplets';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:bd16 ph16 bd16 bd16 ph16 bd16 ph16 ph16 bd16 ph16 bd16 bd16 ph16 bd16 ph16 ph16' WHERE slug = 'foot-paradiddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 bd16 ph16 ph16 bd8 r8]*2' WHERE slug = 'kick-five-stroke';

UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 sn16 sn16 bd16]*4' WHERE slug = 'k-r-r-k';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 bd16 sn16 bd16]*4' WHERE slug = 'r-k-l-k';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 sn16 sn16 sn16]*4' WHERE slug = 'k-r-l-r';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 sn16 bd16 bd16]*4' WHERE slug = 'r-l-k-k';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:(sn8 sn8 bd8)*4' WHERE slug = 'linear-r-l-k';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 sn16 bd16 sn16]*4' WHERE slug = 'k-r-k-l';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 bd16 sn16 sn16 bd16 sn16 r8]*2' WHERE slug = 'r-k-r-l-k-l';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:sn8*8 || bd4 ph4 bd4 ph4' WHERE slug = 'foot-under-eighths';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[sn16 sn16 bd16 sn16 sn16 bd16 r8]*2' WHERE slug = 'linear-six-grouping';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 bd16 sn16 sn16 bd16 bd16 sn16 sn16]*2' WHERE slug = 'double-kick-into-fill';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 sn16 sn16 bd16 bd16 sn16 sn16 bd16]*2' WHERE slug = 'k-r-r-k-diddle';
UPDATE patterns SET vex_feet = NULL, vex_notes = 'drum:[bd16 sn16 sn16 sn16]*4' WHERE slug = 'herta-with-foot';
