/**
 * Shared SFTP helpers (Blaze-parity, Stickitout standalone).
 */
import { existsSync } from 'node:fs';
import { readdir, stat, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(__dirname, '../..');

export function loadEnv() {
  dotenv.config({ path: path.join(REPO_ROOT, '.env') });
}

export function getSftpConfig() {
  const host = process.env.SFTP_HOST?.trim() || process.env.SHIPIT_SFTP_HOST?.trim();
  const username = process.env.SFTP_USER?.trim() || process.env.SHIPIT_SFTP_USER?.trim();
  const password = process.env.SFTP_PASSWORD?.trim() || process.env.SHIPIT_SFTP_PASSWORD?.trim();
  const port = Number(process.env.SFTP_PORT || process.env.SHIPIT_SFTP_PORT || 22);
  const missing = [];
  if (!host) missing.push('SFTP_HOST');
  if (!username) missing.push('SFTP_USER');
  if (!password) missing.push('SFTP_PASSWORD');
  if (missing.length) {
    throw new Error(`Missing ${missing.join(', ')}. Copy .env.example → .env and fill credentials.`);
  }
  return { host, port, username, password, readyTimeout: 20000 };
}

export async function resolveWebRoot(client) {
  const fromEnv = process.env.SFTP_REMOTE?.trim();
  if (fromEnv) return fromEnv.replace(/\/$/, '') || '/';
  for (const candidate of ['/htdocs', '/html', '/public_html', '/www']) {
    if ((await client.exists(candidate)) === 'd') return candidate;
  }
  return '/';
}

async function walkLocalFiles(dir, root = dir) {
  const out = [];
  for (const ent of await readdir(dir, { withFileTypes: true })) {
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) out.push(...(await walkLocalFiles(abs, root)));
    else if (ent.isFile()) out.push({ abs, rel: path.relative(root, abs).split(path.sep).join('/') });
  }
  return out;
}

const DEFAULT_EXCLUDE = [
  'data/leads.json',
  'data/leads.lock',
  'data/capture-config.php',
];

async function ensureRemoteDir(client, remoteDir) {
  if (!remoteDir || remoteDir === '/') return;
  const parts = remoteDir.split('/').filter(Boolean);
  let cur = '';
  for (const part of parts) {
    cur = `${cur}/${part}`;
    const kind = await client.exists(cur);
    if (kind === '-') {
      console.log(`🗑  Removing remote file blocking directory: ${cur}`);
      await client.delete(cur);
    }
  }
  await client.mkdir(remoteDir, true);
}

export async function uploadWithProgress(client, localDir, remoteRoot, opts = {}) {
  const exclude = new Set([...(opts.exclude || []), ...DEFAULT_EXCLUDE]);
  const walked = await walkLocalFiles(localDir);
  const files = [];
  for (const f of walked) {
    if (exclude.has(f.rel) || f.rel.startsWith('data/leads')) continue;
    files.push({ ...f, size: (await stat(f.abs)).size });
  }
  files.sort((a, b) => a.size - b.size);
  const base = remoteRoot.replace(/\/+$/, '') || '';
  console.log(`📦 ${files.length} files → ${base || '/'}/`);

  for (let i = 0; i < files.length; i++) {
    const { abs, rel } = files[i];
    const remotePath =
      base === '' || base === '/'
        ? `/${rel}`.replace(/\/+/g, '/')
        : `${base}/${rel}`.replace(/\/+/g, '/');
    const remoteDir = remotePath.includes('/') ? remotePath.slice(0, remotePath.lastIndexOf('/')) : '/';
    if (remoteDir && remoteDir !== '/') {
      await ensureRemoteDir(client, remoteDir);
    }
    await client.fastPut(abs, remotePath);
    if ((i + 1) % 25 === 0 || i === files.length - 1) {
      console.log(`   ${i + 1}/${files.length}`);
    }
  }
}

/** Escape a value for a single-quoted PHP string. */
function phpQuote(value) {
  return `'${String(value ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Write notify + ingest config into dist before upload (not committed). */
export async function writeCaptureConfig(distDir) {
  const to = (process.env.CAPTURE_NOTIFY_TO || '').trim();
  const from = (process.env.CAPTURE_NOTIFY_FROM || 'noreply@stickitoutbook.com').trim();
  const dataDir = path.join(distDir, 'data');
  await mkdir(dataDir, { recursive: true });
  const ingestUrl = (process.env.LEAD_INGEST_URL || 'https://member.stickitoutdrums.com/api/leads').trim();
  const ingestSecret = (process.env.LEAD_INGEST_SECRET || '').trim();
  // Must be valid PHP array syntax. JSON.stringify objects are invalid PHP and 500 the capture endpoint.
  const php = `<?php
// Generated by ship, do not commit
return [
  'notifyTo' => ${phpQuote(to)},
  'notifyFrom' => ${phpQuote(from)},
  'ingestUrl' => ${phpQuote(ingestUrl)},
  'ingestSecret' => ${phpQuote(ingestSecret)},
];
`;
  await writeFile(path.join(dataDir, 'capture-config.php'), php, 'utf8');
  if (to) console.log(`Capture notify → ${to}`);
  else console.log('Capture notify unset (leads still saved to data/leads.json)');
  if (ingestUrl && ingestSecret) console.log(`Capture ingest → ${ingestUrl}`);
  else console.log('Capture ingest unset (D1/Resend forward disabled)');
}

export function distPath() {
  return path.join(REPO_ROOT, 'dist');
}

export function assertDist() {
  if (!existsSync(distPath())) {
    throw new Error('dist/ missing. Run npm run build first');
  }
}
